// Code generated by "stringer -type ActionTriggerEvent"; DO NOT EDIT.

package configs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventUnknown-0]
	_ = x[EventBeforeCreate-1]
	_ = x[EventAfterCreate-2]
	_ = x[EventBeforeUpdate-3]
	_ = x[EventAfterUpdate-4]
	_ = x[EventBeforeDestroy-5]
	_ = x[EventAfterDestroy-6]
	_ = x[EventInvoke-7]
}

const _ActionTriggerEvent_name = "EventUnknownEventBeforeCreateEventAfterCreateEventBeforeUpdateEventAfterUpdateEventBeforeDestroyEventAfterDestroyEventInvoke"

var _ActionTriggerEvent_index = [...]uint8{0, 12, 29, 45, 62, 78, 96, 113, 124}

func (i ActionTriggerEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ActionTriggerEvent_index)-1 {
		return "ActionTriggerEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionTriggerEvent_name[_ActionTriggerEvent_index[idx]:_ActionTriggerEvent_index[idx+1]]
}
